"use strict";
import "./core";
import "./modules/environment";
import "./modules/color";
import "./modules/collide";
import "./modules/shape";
import "./modules/structure";
import "./modules/dom";
import "./modules/data";
import "./modules/math";
import "./modules/rendering";
import "./modules/transform";
import "./modules/events";
import "./modules/image";
import "./modules/io";
import "./modules/typography";
import "./elements/3d_elements";

const customElementsDefined = new Event("customElementsDefined");
dispatchEvent(customElementsDefined);
